export const SET_CUSTOM_CATEGORIES = "SET_CUSTOM_CATEGORIES";
export const SET_SMART_CATEGORIES = "SET_SMART_CATEGORIES";
export const SET_TAGS = "SET_TAGS";
export const SET_TYPES = "SET_TYPES";
export const SET_MENU_OPEN = "SET_MENU_OPEN";